const images = {
  0: 'avengers-captain.jpg',
  1: 'avengers-ironman.jpg',
  2: 'avengers-thor.jpg',
  3: 'avengers-hulk.jpg',
  4: 'avengers-viuda.jpg',
  5: 'avengers-marvel.jpg',
  6: 'avengers-scarlet.jpg',
  7: 'avengers-spiderman.jpg',
  8: 'avengers-antman.jpg',
  9: 'avengers-starlord.jpg',
  10: 'disney-brave.jpg',
  11: 'disney-elsa.jpg',
  12: 'disney-rapunzel.jpg',
  13: 'disney-vaiana.jpg',
  14: 'disney-wall-e.jpg',
  15: 'disney-incredible.jpg',
  16: 'disney-nemo.jpg',
  17: 'disney-up.jpg',
  18: 'disney-anna.jpg',
  19: 'disney-woody.jpg',
  20: 'hp-draco.jpg',
  21: 'hp-ginny.jpg',
  22: 'hp-harry.jpg',
  23: 'hp-hermione.jpg',
  24: 'hp-luna.jpg',
  25: 'hp-ron.jpg',
  26: 'hp-severus.jpg',
  27: 'hp-voldemort.jpg',
  28: 'hp-dumbledore.jpg',
  29: 'hp-mcgonagall.jpg',
  30: 'sw-chewbacca.jpg',
  31: 'sw-darthVader.jpg',
  32: 'sw-han-solo.jpg',
  33: 'sw-leia.jpg',
  34: 'sw-luke.jpg',
  35: 'sw-r2d2-c3po.jpg',
  36: 'sw-yoda.jpg',
  37: 'sw-bobaffet.jpg',
  38: 'sw-tusken.jpg',
  39: 'sw-ben-kenobi.jpg'
}

export { images };